version: '3.8'

services:

  db:
    user: "root"
    container_name: auth-db
    image: postgres:latest
    restart: always
    ports:
      - 5434:5432
    volumes:
      - ./data/postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=auth
      - POSTGRES_PASSWORD=auth
      - POSTGRES_DB=auth-db
    networks:
      - auth-network

  redis:
    container_name: 'redis'
    image: redis
    restart: always
    ports:
      - '6380:6379'
    environment:
      TZ: 'America/Sao_Paulo'
    networks:
      - auth-network

networks:
  auth-network:
    driver: bridge
